// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const config =  {
    API: {
        GraphQL: {
          endpoint: 'https://wiqbyethxffg7oj2hyjsgapf4q.appsync-api.eu-west-3.amazonaws.com/graphql',
          region: 'eu-west-3',
          defaultAuthMode: 'userPool',
        }
    }
};

export default config;